# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 05:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 8, 57, 7, 405714)),
        ),
    ]
