# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 05:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170607_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 8, 59, 35, 247295)),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 8, 59, 35, 247295)),
        ),
    ]
