# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 06:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170607_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 9, 0, 42, 447144)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 9, 0, 42, 447144)),
        ),
    ]
